### ISSUE TITLE
How to Format or a way to format Python code to emulate. 

### ISSUE THREAD

**Issue by Azuronate** [DylanBruner/VexEmulator#5]
## Describe your changes
A way or method to insert VEX V5 Python with indents OR a way to format it like the example programs with only one line.

## Does this fix any issues? (provide issue numbers)
A lot of confusion. 

## Checklist

- [X] #6

**Comment by DylanBruner** [comment]
What do you mean by one line? Like all of your code on one line? Why would you want to do this?

**Comment by Azuronate** [comment]
Well, with the shipped (default) programs they are all 1 line and have various different parameters. EX: ![image](https://user-images.githubusercontent.com/64029396/202563561-3ec2b456-2905-4a5e-ad0c-a1e387028aee.png)
The above example program works great! I tried to paste in my code from VEX V5 program into it and give it the same file ending "v5.python" that has indents and not on one line but got errors. See: 
![image](https://user-images.githubusercontent.com/64029396/202564278-091683ec-59d4-4fb1-9249-5f607b8e832a.png)
Here is some of the code: 
![image](https://user-images.githubusercontent.com/64029396/202564405-aa4ae025-d3aa-424f-8bca-00f72733937a.png)
I may just be putting it in the wrong place, but not sure. Hopefully you can help me out, and thanks for your time!

**Comment by DylanBruner** [comment]
Can you give me a copy of the code so I can try to reproduce the error?

**Comment by Azuronate** [comment]
> Can you give me a copy of the code so I can try to reproduce the error?

Yep!
[Main.txt](https://github.com/DylanBruner/VexEmulator/files/10047732/Main.txt)

*Made It a text to upload it*

**Comment by DylanBruner** [comment]
Oop. Sorry, I meant the .v5python version not just the raw code.

**Comment by Azuronate** [comment]
> 

I think that's what I'm tripped on. That's what I was trying to use in the emulator and didn't work. Is there a way to format it to .v5python?

**Comment by DylanBruner** [comment]
You just need the file that Vex Code generates it's already in the correct format. It should end in .v5python

It parses the code directly from that, it should work unless vex updated how they save files but I haven't heard anything about them doing so

**Comment by Azuronate** [comment]
Would this work?
https://drive.google.com/file/d/1PCBuec_sDBg6KoKREOMYHSsYJdnGyHh1/view?usp=sharing
Had to upload via drive, Github doesn't allow it to be uploaded in .v5python

**Comment by DylanBruner** [comment]
![image](https://user-images.githubusercontent.com/61059252/202867075-2663ee92-2547-4607-848d-a8e481edecad.png)

**Comment by Azuronate** [comment]
> ![image](https://user-images.githubusercontent.com/61059252/202867075-2663ee92-2547-4607-848d-a8e481edecad.png)

Shared.

**Comment by DylanBruner** [comment]
This should work
`{"mode":"Text","textContent":"#region VEXcode Generated Robot Configuration\nfrom vex import *\nimport urandom\n\n# Brain should be defined by default\nbrain=Brain()\n\n# Robot configuration code\n\n\n# wait for rotation sensor to fully initialize\nwait(30, MSEC)\n#endregion VEXcode Generated Robot Configuration\n\n# ------------------------------------------\n# \n# \tProject:      VEXcode Project\n#\tAuthor:       VEX\n#\tCreated:\n#\tDescription:  VEXcode V5 Python Project\n# \n# ------------------------------------------\n\n# Library imports\nfrom vex import *\n\n#\n# Variables\n#\n\n#0 = empty square \n#1  = orange, end square \n#2 = red, blocked square \n#3 = green, start square\n\npath_4 = [\n    [1, 0, 0, 0, 0],\n    [2, 0, 0, 0, 0],\n    [0, 0, 0, 0, 2],\n    [0, 2, 0, 0, 0],\n    [0, 0, 0, 0, 3]\n]\n\ndef logo():\n   brain.screen.set_pen_width(10)\n   brain.screen.set_pen_color(Color.ORANGE)\n   brain.screen.draw_line(30, 10, 30, 230)\n   brain.screen.draw_line(30, 10, 120, 230)\n   brain.screen.draw_line(120, 10, 120, 230)\n   brain.screen.draw_line(190, 10, 190, 230)\n   brain.screen.draw_rectangle(190, 10, 100, 100)\n   brain.screen.draw_circle(470, 125, 115)\n   brain.screen.set_pen_color(Color.BLACK)\n   brain.screen.draw_rectangle(450, 5, 400, 400)\n   wait(2, SECONDS)\n   brain.screen.set_pen_color(Color.WHITE)\n   brain.screen.clear_screen()\n   brain.screen.set_cursor(1, 1)\n\ndef when_started():\n    logo()\n\nprint(\"Logo\")\nlogo()\nprint(\"Logo\")\n","textLanguage":"python","rconfig":[],"slot":1,"platform":"V5","sdkVersion":"20220726.10.00.00","appVersion":"2.4.0","minVersion":"2.4.0","fileFormat":"1.2.0","icon":"","targetBrainGen":"First","target":"Physical"}`

**Comment by Azuronate** [comment]
Wow! How did you do that? Like what steps do I need to make my code look like that?

**Comment by DylanBruner** [comment]
Just edit it using Vex Code and make sure to leave all the auto generated code at the top alone and it should work!
To get it to work though I pasted the raw code into one of the example programs and it worked
